site_name: Test Project Documentation
repo_url: https://github.com/k1llzz/test.git
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.sections
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/index.md
      - Agent: getting-started/agent/index.md
      - Provider: getting-started/provider/index.md
      - Tool: getting-started/tool/index.md
  - Core concepts:
      - Overview: core-concepts/index.md
      - Diagrams: core-concepts/images/diagrams/index.md
  - Agents:
      - Architecture: agents/architecture.md
      - Communication: agents/communication.md
      - Config: agents/config.md
  - Tools:
      - Architecture: tools/architecture.md
      - Config: tools/config.md
  - Services:
      - Redis: services/redis.md
      - S3: services/s3.md
      - PostgreSQL: services/postgresql.md
      - LightRAG: services/lightrag.md
